create database QuanLyVatTu;

use QuanLyVatTu;

CREATE TABLE VATTU (
    MaVTU CHAR(10) PRIMARY KEY,
    TenVTU NVARCHAR(100)
);

CREATE TABLE PHIEUXUAT (
    SoPX CHAR(10) PRIMARY KEY,
    NgayXuat DATE
);

CREATE TABLE PHIEUNHAP (
    SoPN CHAR(10) PRIMARY KEY,
    NgayNhap DATE
);

CREATE TABLE NHACC (
    MaNCC CHAR(10) PRIMARY KEY,
    TenNCC NVARCHAR(100),
    DiaChi NVARCHAR(200),
    SDT CHAR(15)
);

CREATE TABLE DONDH (
    SoDH CHAR(10) PRIMARY KEY,
    NgayDH DATE,
    MaNCC CHAR(10),
    FOREIGN KEY (MaNCC) REFERENCES NHACC(MaNCC)
);

CREATE TABLE CTPX (
    SoPX CHAR(10),
    MaVTU CHAR(10),
    DGXuat DECIMAL(18,2),
    SLXuat INT,
    PRIMARY KEY (SoPX, MaVTU),
    FOREIGN KEY (SoPX) REFERENCES PHIEUXUAT(SoPX),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CTPN (
    SoPN CHAR(10),
    MaVTU CHAR(10),
    DGNhap DECIMAL(18,2),
    SLNhap INT,
    PRIMARY KEY (SoPN, MaVTU),
    FOREIGN KEY (SoPN) REFERENCES PHIEUNHAP(SoPN),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);

CREATE TABLE CTDDH (
    SoDH CHAR(10),
    MaVTU CHAR(10),
    PRIMARY KEY (SoDH, MaVTU),
    FOREIGN KEY (SoDH) REFERENCES DONDH(SoDH),
    FOREIGN KEY (MaVTU) REFERENCES VATTU(MaVTU)
);